Changed toggleprivaterank
martinmladenov/RankingBot pull request #8
Opened 2020-10-04 10:03 UTC by AntoniosBarotsis

The command now takes a ``programme`` argument and only turns that private instead of all the user's entries. Fixes [this](https://github.com/martinmladenov/RankingBot/issues/6) issue

2020-10-05 18:26 UTC, martinmladenov requested changes
Thanks for your contribution!

There are just a few things I wanted to point out:
- It seems you've removed the return statement of one of the service methods. Could you put it back?
- Can you also make it so that if a user doesn't enter a programme id (i.e. types `.toggleprivaterank` with no argument) but only has a rank for one programme, then an error isn't thrown and the correct rank is automatically modified?
- Could you update the command usage in the message that shows up when there is an input error, as well as in the help file?

2020-10-05 18:26 UTC, martinmladenov commented on services/ranks_service.py
>                                                   user_id)
```suggestion
                                                 user_id)
        return is_private
```
It seems you've accidentally deleted the return statement here

2020-10-05 18:54 UTC, martinmladenov requested changes
Can you use `programmes_helper.get_ids_string()` in the error messages so that a more user-friendly string is generated and printed?

2020-10-05 19:05 UTC, AntoniosBarotsis commented
No

2020-10-06 16:36 UTC, martinmladenov approved these changes

2020-10-06 16:38 UTC, merged